project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "examples/**/*.ipynb"
    - "!examples/r_simmer/"
    - "!examples/ARCHIVE_vidigi_vs_bupar/"

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: vidigi
  description: "Documentation for the vidigi pathway animation package"
  back-to-top-navigation: true
  page-footer:
    center: |
      [![](/vidigi_docs/assets/hsma_logo.png){width=150px}](https://www.hsma.co.uk/)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      [![](/vidigi_docs/assets/nihr_logo.png){width=250px}](https://arc-swp.nihr.ac.uk/)<br/><br/>
      *This work is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.<br/>
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
      <br/><br/>
  # 1. TOP NAVIGATION BAR (High-level splits)
  navbar:
    search: true
    left:
      - text: "Home"
        href: vidigi_docs/index.qmd
      - text: "Getting Started"
        href: vidigi_docs/getting_started.qmd
      - text: "Examples"
        href: examples/examples.qmd
      - text: "Feature Breakdowns"
        href: examples/feature_breakdowns.qmd
      - text: "API Reference"
        href: reference/index.qmd
      - href: vidigi_docs/changelog.qmd
        text: "Changelog"
      - text: "Package Details"
        menu:
          - href: vidigi_docs/licence.qmd
            text: "Licence"
          - href: vidigi_docs/code_of_conduct.qmd
            text: "Code of Conduct"
          - href: vidigi_docs/attribution_for_examples.qmd
    right:
      - icon: github
        href: https://github.com/hsma-tools/vidigi
      - icon: box-fill
        href: https://pypi.org/project/vidigi/

  # 2. SIDEBARS (Context-specific)
  sidebar:
    # --- Sidebar: API Reference (Generated by Quartodoc) ---
    - title: "Reference"
      id: "reference"
      match-path: "reference/*" # Matches the quartodoc output dir
      contents:
        - _sidebar.yml # Include the file quartodoc generates
      style: floating


# 3. QUARTODOC CONFIGURATION (Purely for API)
quartodoc:
  dir: reference
  out_index: index.qmd
  package: vidigi

  # Write the API structure to this file
  sidebar:
    file: "_sidebar.yml"
    style: floating
    collapse-level: 3
    # ONLY include the placeholder here. We moved the manual stuff up to `website`
    contents:
      - "{{ contents }}"

  # Define the Python objects to document
  sections:
    - title: All-In-One Animation Functions
      desc: ""
      contents:
        - animation.animate_activity_log
    - title: Step-By-Step Functions
      desc: ""
      contents:
        - prep.reshape_for_animations
        - prep.generate_animation_df
        - animation.generate_animation
    - title: Animation Enhancers
      desc: ""
      contents:
        - animation.add_repeating_overlay
    - title: Simpy Resource Classes
      desc: ""
      contents:
        - resources.VidigiResource
        - resources.VidigiStore
        - resources.VidigiPriorityStore
        - resources.populate_store
    - title: Event Logging Utility Functions and Classes
      desc: ""
      contents:
        - logging.EventLogger
        - logging.TrialLogger
    - title: Event Positioning Utility Functions and Classes
      desc: ""
      contents:
        - utils.EventPosition
        - utils.create_event_position_df
    - title: Process Map-Style Outputs
      desc: ""
      contents:
        - process_mapping.add_sim_timestamp
        - process_mapping.discover_dfg
        - process_mapping.dfg_to_graphviz
        - process_mapping.process_nodes_and_edges_for_cytoscape
        - process_mapping.dfg_to_cytoscape
        - process_mapping.dfg_to_cytoscape_streamlit
    - title: Streamlit Utility Functions
      desc: ""
      contents:
        - utils.streamlit_play_all
    - title: ciw Utility Functions
      desc: ""
      contents:
        - ciw.event_log_from_ciw_recs
    - title: legacy Functions
      desc: ""
      contents:
        - resources.VidigiPriorityStoreLegacy

format:
  html:
    grid:
      sidebar-width: 325px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 1.5rem
    execute:
      freeze: auto
    theme:
      dark: [darkly, theme-dark.scss]
      light: [flatly, theme-light.scss]
    css: vidigi_docs/styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
