name: vidigi_package_dev
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - hatch
  - ipywidgets=8.1.5
  - jupyterlab=4.2.4
  - jupyterlab-spellchecker=0.8.4
  - libtiff=4.5.1
  - matplotlib=3.9.1
  - nbqa
  - numpy=1.26.2
  - pandas=2.0.1
  - plotly=6.1.1
  - pillow=10.0.0
  - pip=24.0
  - pydantic=2.10.4
  - python=3.11
  - pytest=8.3.2
  - pytest-html=4.1.1
  - quartodoc=0.9.1
  - simpy=4.0.2
  - sim-tools=0.9.0
  - tox=4.25.0
  - webcolors=24.11.1
  - pip:
    - ciw==3.2.5
    - -e ../vidigi