# Function reference {.doc .doc-index}

## All-In-One Animation Functions



| | |
| --- | --- |
| [animation.animate_activity_log](animation.animate_activity_log.qmd#vidigi.animation.animate_activity_log) |     Generate an animated visualization of patient flow through a system. |

## Step-By-Step Functions



| | |
| --- | --- |
| [prep.reshape_for_animations](prep.reshape_for_animations.qmd#vidigi.prep.reshape_for_animations) | Reshape event log data for animation purposes. |
| [prep.generate_animation_df](prep.generate_animation_df.qmd#vidigi.prep.generate_animation_df) | Generate a DataFrame for animation purposes by adding position information to entity data. |
| [animation.generate_animation](animation.generate_animation.qmd#vidigi.animation.generate_animation) |     Generate an animated visualization of patient flow through a system. |

## Animation Enhancers



| | |
| --- | --- |
| [animation.add_repeating_overlay](animation.add_repeating_overlay.qmd#vidigi.animation.add_repeating_overlay) |  Add a repeating overlay (rectangle and text) to an animated Plotly figure using traces. |

## Simpy Resource Classes



| | |
| --- | --- |
| [resources.VidigiResource](resources.VidigiResource.qmd#vidigi.resources.VidigiResource) | A simple resource class with an ID attribute for use in VidigiStore and VidigiPriorityStore. |
| [resources.VidigiStore](resources.VidigiStore.qmd#vidigi.resources.VidigiStore) | A wrapper around SimPy's Store that allows using a context manager pattern |
| [resources.VidigiPriorityStore](resources.VidigiPriorityStore.qmd#vidigi.resources.VidigiPriorityStore) | An optimized SimPy priority store that eliminates delays between resource |
| [resources.populate_store](resources.populate_store.qmd#vidigi.resources.populate_store) | Populate a SimPy Store (or VidigiPriorityStore) with VidigiResource objects. |

## Event Logging Utility Functions and Classes



| | |
| --- | --- |
| [logging.EventLogger](logging.EventLogger.qmd#vidigi.logging.EventLogger) |  |
| [logging.TrialLogger](logging.TrialLogger.qmd#vidigi.logging.TrialLogger) | A container and analysis utility for managing multiple event logs from repeated |

## Event Positioning Utility Functions and Classes



| | |
| --- | --- |
| [utils.EventPosition](utils.EventPosition.qmd#vidigi.utils.EventPosition) | Pydantic model for a single event position. |
| [utils.create_event_position_df](utils.create_event_position_df.qmd#vidigi.utils.create_event_position_df) | Creates a DataFrame for event positions from a list of EventPosition objects. |

## Process Map-Style Outputs



| | |
| --- | --- |
| [process_mapping.add_sim_timestamp](process_mapping.add_sim_timestamp.qmd#vidigi.process_mapping.add_sim_timestamp) | Add a pseudo-timestamp column to a simulation event log. |
| [process_mapping.discover_dfg](process_mapping.discover_dfg.qmd#vidigi.process_mapping.discover_dfg) | Discover a Directly-Follows Graph (DFG) from an event log. |
| [process_mapping.dfg_to_graphviz](process_mapping.dfg_to_graphviz.qmd#vidigi.process_mapping.dfg_to_graphviz) | Render a Directly-Follows Graph (DFG) as a Graphviz diagram. |
| [process_mapping.process_nodes_and_edges_for_cytoscape](process_mapping.process_nodes_and_edges_for_cytoscape.qmd#vidigi.process_mapping.process_nodes_and_edges_for_cytoscape) | Convert DFG node and edge tables into Cytoscape-compatible elements. |
| [process_mapping.dfg_to_cytoscape](process_mapping.dfg_to_cytoscape.qmd#vidigi.process_mapping.dfg_to_cytoscape) | Convert DFG node/edge tables to interactive Cytoscape widget. |
| [process_mapping.dfg_to_cytoscape_streamlit](process_mapping.dfg_to_cytoscape_streamlit.qmd#vidigi.process_mapping.dfg_to_cytoscape_streamlit) | Render a Directly-Follows Graph (DFG) interactively in Streamlit using Cytoscape. |

## Streamlit Utility Functions



| | |
| --- | --- |
| [utils.streamlit_play_all](utils.streamlit_play_all.qmd#vidigi.utils.streamlit_play_all) | Programmatically triggers all 'Play' buttons in Plotly animations embedded in Streamlit using JavaScript. |

## ciw Utility Functions



| | |
| --- | --- |
| [ciw.event_log_from_ciw_recs](ciw.event_log_from_ciw_recs.qmd#vidigi.ciw.event_log_from_ciw_recs) | Given the ciw recs object, return a dataframe in the format expected by the vidigi |

## legacy Functions



| | |
| --- | --- |
| [resources.VidigiPriorityStoreLegacy](resources.VidigiPriorityStoreLegacy.qmd#vidigi.resources.VidigiPriorityStoreLegacy) | A SimPy store that processes requests with priority. |