# utils.EventPosition { #vidigi.utils.EventPosition }

```python
utils.EventPosition()
```

Pydantic model for a single event position.

This model defines the position and label of an event within a visual layout.
Coordinates represent the bottom-right corner of a queue or resource, and an
optional label or resource can be associated with the event.

## Attributes {.doc-section .doc-section-attributes}

| Name     | Type            | Description                                                                                                                                                 |
|----------|-----------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| event    | str             | The name of the event. Must match the event names as they appear in your event log.                                                                         |
| x        | int             | The x-coordinate for the event. Represents the bottom-right corner of the queue or resource.                                                                |
| y        | int             | The y-coordinate for the event. Represents the bottom-right corner of the queue or resource.                                                                |
| label    | str             | The display label for the event. Used if `display_stage_labels=True`. Allows for a more user-friendly version of the event name (e.g., 'Queuing for Till'). |
| resource | Optional\[str\] | The optional resource associated with the event. Must match a resource name provided in your scenario object.                                               |