name: Documentation Against PyPI Release

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version"
        required: true
        default: "3.12"
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >
            ${{ runner.os }}-pypi-docs-
            ${{ github.event.inputs.python-version }}-
            ${{ hashFiles('dev_environment/requirements.txt') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        run: |
          pip install -r dev_environment/requirements.txt

      - name: Install latest Vidigi from PyPI
        run: |
          pip install vidigi

      - name: Show installed version
        run: |
          python -c "import vidigi; print(vidigi.__version__)"

      - name: Render documentation
        run: |
          quarto render examples/ --execute
