name: Upload Python Package

on:
  release:
    types: [published]

# Add the 'id-token: write' permission to allow the workflow to request an OIDC token
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch

    - name: Build package
      run: hatch build

    # The 'user' and 'password' fields are removed.
    # The action will automatically use OIDC authentication.
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
